name: Update Departures File

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    paths:
      - getDepartures.bash
      - .github/workflows/extract.yml
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  update_departures:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "America/New_York"
        timezoneMacos: "America/New_York"
        timezoneWindows: "America/New_York"

    - name: Set up the environment (install dependencies)
      run: |
        sudo apt-get update
        sudo apt-get install -y bash

    - name: Run the getDepartures.bash script
      run: |
        chmod +x getDepartures.bash
        ./getDepartures.bash

    - name: Remove departures.json from history
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Remove the file from history to ensure no previous versions exist
        git config --global user.name "Shekar"
        git config --global user.email "shekar@yahoo.com"
        git rm --cached departures.json
        git commit -m "Remove departures.json from previous history"

    - name: Commit departures.json with no history
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "Shekar"
        git config --global user.email "shekar@yahoo.com"
        git add departures.json
        git commit -m "Add new departures.json (no history)"
        git push origin main --force
